target("cpu_demo")
    set_kind("binary")
    add_includedirs("../../include")
    add_headerfiles("../../include/**/*.hpp")
    add_files("main.cpp")
    add_packages("cli11", "spdlog", "openmp", "glm")
    add_deps("kernels")
